# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
