# Generated by Django 2.2.4 on 2019-08-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190822_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='', upload_to='articles/'),
        ),
    ]
