# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_delete_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post',
            field=models.TextField(),
        ),
    ]
