# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-03 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190828_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, default='', upload_to='articles/'),
        ),
    ]
