# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-03 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190903_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='articles/'),
        ),
    ]
