# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-04 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190903_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post',
            field=models.TextField(),
        ),
    ]
